apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command:
            - /bin/bash
            - -c
            - |
              sleep 10
              curl -X POST -H 'Content-type: application/json' --data '{"text":"Post sync is done!"}' https://hooks.slack.com/services/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

      restartPolicy: Never
  backoffLimit: 0
