apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: kubectl:latest
          command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
