apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: test
          image: bitnami/kubectl
          command:
            - "bin/bash"
            - "-c"
            - "kubectl get pods"
      restartPolicy: Never
  backoffLimit: 0
